CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Une application existante peut déjà contenir des tâches. Elles sont conservées
-- dans un compte technique non utilisable, plutôt que d'être perdues.
INSERT INTO app_users (email, password_hash)
VALUES ('legacy@taskflow.local', '$2a$10$y6u0H0E3ql7S1QLD.FWcGuObvS5Kxxe5sKi4KN.2PbsYTlS0LruLy');

ALTER TABLE tasks ADD COLUMN owner_id BIGINT;
UPDATE tasks SET owner_id = (SELECT id FROM app_users WHERE email = 'legacy@taskflow.local');
ALTER TABLE tasks ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_tasks_owner FOREIGN KEY (owner_id) REFERENCES app_users(id);
