CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES app_users(id),
    CONSTRAINT uk_projects_owner_name UNIQUE (owner_id, name)
);

ALTER TABLE tasks ADD COLUMN project_id BIGINT REFERENCES projects(id) ON DELETE SET NULL;
