CREATE TABLE daily_priorities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  priority_date DATE NOT NULL,
  position INTEGER NOT NULL CHECK (position BETWEEN 1 AND 3),
  CONSTRAINT uk_daily_priority_task UNIQUE (owner_id, task_id, priority_date),
  CONSTRAINT uk_daily_priority_position UNIQUE (owner_id, priority_date, position)
);
